// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:144403502567:web:3908d27b32a9e0aeaad942',
    messagingSenderId: '144403502567',
    projectId: 'skin-sync-a0b45',
    authDomain: 'skin-sync-a0b45.firebaseapp.com',
    storageBucket: 'skin-sync-a0b45.firebasestorage.app',
    measurementId: 'G-C5MHXEDWM0',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:144403502567:ios:9d1bc5a31a261770aad942',
    messagingSenderId: '144403502567',
    projectId: 'skin-sync-a0b45',
    storageBucket: 'skin-sync-a0b45.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:144403502567:ios:9d1bc5a31a261770aad942',
    messagingSenderId: '144403502567',
    projectId: 'skin-sync-a0b45',
    storageBucket: 'skin-sync-a0b45.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:144403502567:web:e0fb0c9a89ee7d78aad942',
    messagingSenderId: '144403502567',
    projectId: 'skin-sync-a0b45',
    authDomain: 'skin-sync-a0b45.firebaseapp.com',
    storageBucket: 'skin-sync-a0b45.firebasestorage.app',
    measurementId: 'G-8KDNM2SMR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:144403502567:android:058749379bc943d9aad942',
    messagingSenderId: '144403502567',
    projectId: 'skin-sync-a0b45',
    storageBucket: 'skin-sync-a0b45.firebasestorage.app',
  );

}